packages:
  - packages/auth-api
  - packages/auth-react
  - packages/cli
  - packages/code-merger
  - packages/create-plasmic-app
  - packages/data-sources
  - packages/data-sources-context
  - packages/host
  - packages/loader-core
  - packages/loader-edge
  - packages/loader-fetcher
  - packages/loader-gatsby
  - packages/loader-nextjs
  - packages/loader-react
  - packages/loader-splits
  - packages/loader-svelte
  - packages/loader-vue
  - packages/nextjs-app-router
  - packages/prepass
  - packages/query
  - packages/react-web
  - packages/react-web-runtime
  - packages/watcher
  - plasmicpkgs/airtable
  - plasmicpkgs/antd
  - plasmicpkgs/antd5
  - plasmicpkgs/chakra-ui
  - plasmicpkgs/commerce-providers/*
  - plasmicpkgs/framer-motion
  - plasmicpkgs/keen-slider
  - plasmicpkgs/lottie-react
  - plasmicpkgs/plasmic-basic-components
  - plasmicpkgs/plasmic-calendly
  - plasmicpkgs/plasmic-cms
  - plasmicpkgs/plasmic-content-stack
  - plasmicpkgs/plasmic-contentful
  - plasmicpkgs/plasmic-embed-css
  - plasmicpkgs/plasmic-eventbrite
  - plasmicpkgs/plasmic-giphy
  - plasmicpkgs/plasmic-graphcms
  - plasmicpkgs/plasmic-hubspot
  - plasmicpkgs/plasmic-nav
  - plasmicpkgs/plasmic-pigeon-maps
  - plasmicpkgs/plasmic-query
  - plasmicpkgs/plasmic-rich-components
  - plasmicpkgs/plasmic-sanity-io
  - plasmicpkgs/plasmic-soundcloud
  - plasmicpkgs/plasmic-strapi
  - plasmicpkgs/plasmic-tabs
  - plasmicpkgs/plasmic-typeform
  - plasmicpkgs/plasmic-wordpress
  - plasmicpkgs/plasmic-wordpress-graphql
  - plasmicpkgs/plasmic-yotpo
  - plasmicpkgs/radix-ui
  - plasmicpkgs/react-aria
  - plasmicpkgs/react-audio-player
  - plasmicpkgs/react-awesome-reveal
  - plasmicpkgs/react-chartjs-2
  - plasmicpkgs/plasmic-link-preview
  - plasmicpkgs/react-parallax-tilt
  - plasmicpkgs/react-quill
  - plasmicpkgs/tiptap
  - plasmicpkgs/react-scroll-parallax
  - plasmicpkgs/react-slick
  - plasmicpkgs/react-twitter-widgets
  - plasmicpkgs/react-youtube
  - platform/canvas-packages
  - platform/canvas-packages/internal_pkgs/react-slick
  - platform/host-test
  - platform/integration-tests
  - platform/live-frame
  - platform/loader-html-hydrate
  - platform/loader-tests
  - platform/react-web-bundle
  - platform/sub
  # wab still performs a postinstall patch-package which isn't kosher with pnpm. But can look into pnpm patch.
  # - platform/loader-bundle-env
#  - platform/wab
#  - platform/wab/create-react-app-new/packages/*
